services:
  frontend:
    build:
      context: ./example-frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - "5000:5000"

  backend:
    build: ./example-backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - PORT=8080
