services:
  frontend:
    build:
      context: ./example-frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./example-backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
#      - POSTGRES_PORT=5432
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  redis:
    image: redis:6
    restart: unless-stopped

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_HOST=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_DATABASE=postgres
