services:
  frontend:
    build:
      context: ./example-frontend
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000/api #nginx:8000/api #localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./example-backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:8000 #nginx:8000 #localhost:8000
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  redis:
    image: redis:6
    restart: unless-stopped

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data # bind mount here
  
  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
